name: featurebase
description: "Featurebase Unofficial Flutter SDK"
version: 0.9.0
homepage: https://github.com/ae1dev/flutter_featurebase

platforms:
  android:
  ios:
  linux:
  macos:
  windows:

topics:
  - featurebase
  - help-center
  - changelog

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  dio: ^5.9.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  flutter_riverpod: ^3.0.0
  riverpod_annotation: ^3.0.0
  url_launcher: ^6.3.2
  custom_top_navigator_plus: ^0.0.4
  flutter_svg: ^2.2.1
  flutter_widget_from_html: ^0.17.1
  cached_network_image: ^3.4.1
  styled_text: ^9.0.0-beta-4
  searchfield: ^1.3.5
  easy_infinite_pagination: ^0.0.6
  universal_io: ^2.2.2
  timeago: ^3.7.0
  collection: ^1.18.0
  copy_with_extension: ^10.0.0
  share_plus: ^12.0.0
  image_picker: ^1.2.0
  fb_core: ^0.0.1
    # git:
    #   url: https://github.com/ae1dev/fb_core.git

dependency_overrides:
  analyzer: ^8.1.1
  analyzer_plugin: ^0.13.7
  custom_lint_visitor: 1.0.0+8.1.1

dev_dependencies:
  flutter_lints: ^5.0.0
  build_runner: ^2.8.0
  custom_lint: ^0.8.1
  riverpod_generator: ^3.0.0
  riverpod_lint: ^3.0.0
  freezed: ^3.2.3
  source_gen: ^4.0.1
  json_serializable: ^6.11.1
  flutter_gen: ^5.11.0
  copy_with_extension_gen: ^10.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/hero/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_28pt_Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter_28pt_Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_28pt_SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter_28pt_Bold.ttf
          weight: 700
